name: Feature request
description: Suggest an idea for HyperChat
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: These are some simple guidelines for creating a bug report, make sure your bug report follows all of these guidelines before submitting
      options:
        - label: This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
          required: true
        - label: I have checked for a duplicate or similar issue. I made sure to check closed issues as well. 
          required: true
        - label: I am not reporting a bug. If I am, I will use the bug report issue template.
          required: true
        - label: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/develop/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of the feature you're suggesting.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What's supposed to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
